added code to my files
Szpytowski/credit-card-css-selectors pull request #1
Opened 2024-08-26 23:25 UTC by Szpytowski

I created this branch so you can evaluate my code

2024-08-27 15:23 UTC, Solnick requested changes
![image](https://github.com/user-attachments/assets/acc963fd-ba9a-4f93-93b5-05d49fc881f4)
The font is different

2024-08-27 15:26 UTC, Solnick requested changes

2024-08-27 15:26 UTC, Solnick commented on css/style.css
> +    position: absolute;
please don't use `position: absolute;` if you don't have to

2024-08-31 08:53 UTC, Szpytowski commented on css/style.css
> +    height: 35px;
I also corrected this because when zooming in and out, it became a mess. I know understand not to use vh to position things.

2024-09-03 12:04 UTC, Solnick approved these changes

2024-09-03 12:33 UTC, merged